# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 454541648ccb1c74d653e87fc6a35e236d8c230479cdd78d4c18f0bdd98675af63b8b636cab85a8210c878910ed8b2ffc63cfbe9010b74354cf72c09e9b5ac74

test:
  secret_key_base: 9e93960bcf9de745c83fdb9faeeae1e88b99854fc76404eba9811ab90e5e212987f5cf78fb83c506a0819952e75174b660e98330a36587f2fb8b7fff658c774d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
